Bugfix/gitignore goed instellen
Ragazzoforte/23.24-D-Softwareontwikkeling pull request #30
Opened 2024-04-29 10:33 UTC by TimWannet

Repo's /build en /debug verwijderd van de /gitignore.
Bestanden in deze map worden aangemaakt/aangepast wanneer het programma "build".
Deze hoeven alleen local te zijn en niet gedeeld via github.

2024-04-30 07:50 UTC, Ragazzoforte approved these changes, later dismissed

2024-04-30 09:07 UTC, tijmcraft requested changes
Ik krijg nogsteeds 14 changes zodra ik de code upload :(
![image](https://github.com/Ragazzoforte/23.24-D-Softwareontwikkeling/assets/52678583/edb1f4d1-b5da-4ec8-8125-18d005770a9f)

2024-05-06 12:46 UTC, tijmcraft approved these changes

2024-05-06 12:47 UTC, Ragazzoforte approved these changes

2024-05-06 12:47 UTC, merged